# Generated by Django 3.2.12 on 2023-07-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
